### ISSUE TITLE
Todo App 요구사항 명세서 작성

### ISSUE THREAD

**Issue by Leewang31** [Leewang31/fe-sprint-framework-practice#1]
### 🌟만들고자 하는 기능이 무엇인가?
todo 생성 기능

### ✨해당 기능을 구현하기 위해 할 일이 무엇인가?
1. [ ] 서버에 todo list를 화면에 출력한다
2. [ ] 서버에 todo list를 추가한다
3. [ ] 서버에 todo list를 삭제한다
4. [ ] 서버에 todo list를 수정한다

### ✨예상 작업 시간
6h
